import type { Metadata } from "next";
import "./globals.css";
import { Inter } from  'next/font/google'


const fonte = Inter({
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pf-BR" dir="ltr">
      <body
        className={fonte.className}>
        {children}
      </body>
    </html>
  );
}
